CREATE TABLE `diary_points` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`date` DATE NOT NULL,
	`text` TEXT NOT NULL,
	`state` ENUM('INITIAL', 'SATISFIED', 'NOT_SATISFIED', 'CANCELED') NOT NULL DEFAULT 'INITIAL'
) ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;
