version: "3"
services:
  wizard-diary:
    build: .
    container_name: wizard-diary
    ports:
      - 80:80
    command:
      - /usr/local/bin/wait-for-it.sh
      - mysql:3306
      - --
      - apache2-foreground
    restart: unless-stopped

  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: diary
      MYSQL_PASSWORD: diary
      MYSQL_DATABASE: diary
    ports:
      - 3306:3306
      - 33060:33060
    restart: unless-stopped

  adminer:
    image: adminer:4.8.1
    ports:
      - 9090:8080
    restart: unless-stopped

  ofelia:
    image: mcuadros/ofelia:v0.3.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./tools/ofelia_config.ini:/etc/ofelia/config.ini:ro
    restart: unless-stopped
